server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /generator

spring:
  profiles:
    active: ${PROFILE_ACTIVE}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}